/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description List stored files, filtered and paginated per docs/design/api.md.
         *
         *     `?fields=full` returns the same shape as `GET /files/{name}/info` for
         *     every row instead of the default light `{name, duration_seconds}` — see
         *     docs/design/api.md for why this is opt-in rather than the default.
         */
        get: operations["list_files_files_get"];
        put?: never;
        /**
         * Upload File
         * @description Upload raw WAV bytes, storing the object then the metadata row.
         */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Stream the stored audio bytes back to the caller.
         */
        get: operations["download_file_files__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete File
         * @description Delete a stored file's metadata row and its object.
         *
         *     Deletes the row before the object, the reverse of the write order in
         *     `POST /files` (see docs/design/api.md), so a crash between the two
         *     leaves an orphaned object rather than a row pointing at a missing one.
         */
        delete: operations["delete_file_files__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{name}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File Info
         * @description Return the full metadata record for a stored file.
         */
        get: operations["get_file_info_files__name__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FileInfo
         * @description Full metadata record, returned by upload and by `GET /files/{name}/info`.
         */
        FileInfo: {
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Sample Rate */
            sample_rate: number;
            /** Channels */
            channels: number;
            /** Bit Depth */
            bit_depth: number;
            /** Codec */
            codec: string;
            /** Sample Format */
            sample_format: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FileListItem
         * @description One entry in the `GET /files` listing: name and duration only.
         *
         *     ``extra="forbid"`` matters here: without it, a `FileInfo`-shaped dict
         *     validates against this narrower model too (extra fields silently
         *     ignored), and Pydantic's union matching in `FileListResponse.items`
         *     can pick this model over `FileInfo` and silently truncate a
         *     `?fields=full` row down to just these two fields.
         */
        FileListItem: {
            /** Name */
            name: string;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /**
         * FileListResponse
         * @description Pagination envelope for `GET /files`.
         *
         *     `items` is `FileListItem` by default, or `FileInfo` when the caller
         *     passes `?fields=full` (see `routes.list_files`).
         */
        FileListResponse: {
            /** Items */
            items: components["schemas"]["FileListItem"][] | components["schemas"]["FileInfo"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_files_files_get: {
        parameters: {
            query?: {
                name?: string[] | null;
                channels?: number[] | null;
                sample_format?: string[] | null;
                codec?: string[] | null;
                sample_rate?: number[] | null;
                min_duration?: number | null;
                max_duration?: number | null;
                min_created_at?: string | null;
                max_created_at?: string | null;
                limit?: number;
                offset?: number;
                fields?: "full" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_files__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_files__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_info_files__name__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
